### ISSUE TITLE
TTreeView类名不对

### ISSUE THREAD

**Issue by bstaint** [ying32/rust-vcl#7]
今天试着给TTreeView添加CheckBox样式：
```
        unsafe {
            let style = GetWindowLongW(self.tv.Handle() as cHWND, GWL_STYLE);
            SetWindowLongW(self.tv.Handle() as cHWND, GWL_STYLE, style | TVS_CHECKBOXES as i32);
        }
```
发现无效，用spy++看了下，好像TTreeView控件的类名不对吧：
![1](https://user-images.githubusercontent.com/5853792/90889204-45bba800-e3ea-11ea-9f7b-eb28c1eb8baa.jpg)

**Comment by ying32** [comment]
不是类名的问题，这个以前就试过，在Lazarus中都不生效，，没具体分析过为什么。。。。

**Comment by bstaint** [comment]
好吧 感谢回复。
